-- Developer: API Reference — lark.* host API quick reference.

lark.register({
    on_run = function()
        return {
            title = "Lark Plugin API",
            raw_text = table.concat({
                "\027[1m\027[36m  ── lark.* Host API Reference ──\027[0m",
                "",
                "\027[1m  lark.register({ on_run = function() ... end })\027[0m",
                "  Entry point. on_run returns { title, items, raw_text, form }.",
                "",
                "\027[1m  lark.exec(command, {args})\027[0m → string",
                "  Run a subprocess. Returns stdout as string.",
                "  Example: lark.exec(\"git\", { \"status\", \"--short\" })",
                "",
                "\027[1m  lark.env(key)\027[0m → string | nil",
                "  Read environment variable. Checks .env → process env → Keychain.",
                "  Example: lark.env(\"HOME\"), lark.env(\"GITHUB_TOKEN\")",
                "",
                "\027[1m  lark.http.get(url, opts)\027[0m → { status, body }",
                "  HTTP GET. opts: { headers = {}, timeout = N }",
                "  Always use resp.body for content, resp.status for HTTP code.",
                "",
                "\027[1m  lark.http.post(url, body, opts)\027[0m → { status, body }",
                "  HTTP POST. body is a string.",
                "",
                "\027[1m  lark.json.encode(table)\027[0m → string",
                "\027[1m  lark.json.decode(string)\027[0m → table",
                "  Use pcall: local ok, data = pcall(lark.json.decode, resp.body)",
                "",
                "\027[1m  lark.store.get(key)\027[0m → value | nil",
                "\027[1m  lark.store.set(key, value)\027[0m",
                "\027[1m  lark.store.delete(key)\027[0m",
                "\027[1m  lark.store.keys()\027[0m → table",
                "  Persistent per-plugin key-value store.",
                "",
                "\027[1m  lark.log(message)\027[0m — Write to tracing log.",
                "\027[1m  lark.form_values\027[0m — Form values after submission (nil first run).",
                "",
                "\027[36m  ── Output Format ──\027[0m",
                "",
                "  return {",
                "    title = \"My Plugin\",",
                "    items = { { label, detail, icon, copy_text, actions } },",
                "    -- OR: raw_text = \"ANSI text\"",
                "    -- OR: form = { fields = {...}, submit_label = \"Go\" }",
                "  }",
                "",
                "  actions = {",
                "    { label, kind = \"shell\", args = {\"cmd\", \"arg\"} },",
                "    { label, kind = \"clipboard\", args = {\"text\"} },",
                "  }",
                "",
                "\027[36m  ── Sandbox ──\027[0m",
                "",
                "  Available: string, table, math, utf8, pcall, pairs, ipairs",
                "  NOT available: os, io, require, loadfile",
                "  Use lark.env() not os.getenv(), lark.exec() not os.execute()",
                "",
            }, "\n"),
        }
    end,
})
